### ISSUE TITLE
update-core not found

### ISSUE THREAD

**Issue by okonomiyaki3000** [msys2-contrib/mingw-w64#3]
Since the most recent update (was it a day or two ago?) `update-core` no longer works. I just get 'command not found'. Was it removed intentionally? Is there another way to do updates now?

**Comment by Alexpux** [comment]
It removed. See WIKI

**Comment by okonomiyaki3000** [comment]
Ah, that's interesting. Which wiki would that be?

**Comment by Alexpux** [comment]
https://sourceforge.net/p/msys2/wiki/MSYS2%20installation/

**Comment by Alexpux** [comment]
And why you post issue there instead https://github.com/Alexpux/MSYS2-packages?

**Comment by Alexpux** [comment]
I close issues here
